import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import { Roboto } from 'next/font/google';
import "./globals.css";

const roboto = Roboto({
  variable: "--font-reboto",
  subsets: ['latin'],
  weight: "100"
});

/*onst geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});*/

/*const customFont = GoogleFont({
  family: 'Geist', // Substitua por uma fonte válida, caso Geist não exista
  subsets: ['latin'],
});*/

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${roboto.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
